-- Officers List: Ministry of Social Welfare (MSW)
-- Generated from 'MSW_Officers_List_by_Department__2_.xlsx' (All Officers sheet)
-- MySQL dialect

DROP TABLE IF EXISTS `msw_officers`;
CREATE TABLE `msw_officers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `overall_sl` INT DEFAULT NULL,
  `department` VARCHAR(255) DEFAULT NULL,
  `sl` INT DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `officer_id` VARCHAR(100) DEFAULT NULL,
  `designation` VARCHAR(255) DEFAULT NULL,
  `office` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `phone_office` VARCHAR(100) DEFAULT NULL,
  `mobile` VARCHAR(100) DEFAULT NULL,
  `intercom` VARCHAR(100) DEFAULT NULL,
  `room_no` VARCHAR(255) DEFAULT NULL,
  `fax` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `msw_officers` (`overall_sl`, `department`, `sl`, `name`, `officer_id`, `designation`, `office`, `email`, `phone_office`, `mobile`, `intercom`, `room_no`, `fax`) VALUES
  ('1', 'Honorable Minister\'s Office', '1', 'Prof. Dr. A Z M Zahid Hossain, MP', NULL, 'Honorable Minister', 'Ministry of Social Welfare', 'minister@msw.gov.bd', '+880 9514643', NULL, NULL, NULL, NULL),
  ('2', 'Honorable Minister\'s Office', '2', 'Dr. MD. Mahmudul Hoque', NULL, 'Private Secretary to the Honorable Minister', 'Ministry of Social Welfare', 'psmin@msw.gov.bd', '+880 55100941', '+880 1806-577599', NULL, '224', NULL),
  ('3', 'Honorable Minister\'s Office', '3', 'Dr. Md. Javed Hossain', NULL, 'Assistant Private Secretary to the Honorable Minister', 'Ministry of Social Welfare', 'javed38mmo@gmail.com', NULL, '+880 1914-857701', NULL, '220', NULL),
  ('4', 'Honorable Minister\'s Office', '4', 'Md. Rafiqul Islam', NULL, 'Public Relations Officer', 'Ministry of Social Welfare', 'pro@msw.gov.bd', NULL, '01718-723815', NULL, NULL, NULL),
  ('5', 'Honorable Minister\'s Office', '5', 'Mohammad Shahadat Hossain', NULL, 'Personal Officer (Office of the Hon\'ble Minister)', 'Ministry of Social Welfare', 'hshahadat.dhaka@gmail.com', '9514643', '01853877987', NULL, NULL, NULL),
  ('6', 'Honorable Minister\'s Office', '6', 'Kallol Ray', NULL, 'Administrative Officer (Office of the Hon\'ble Minister)', 'Ministry of Social Welfare', 'kalloiraymsw@gmail.com', NULL, '01531978675', NULL, NULL, NULL),
  ('7', 'Honorable Minister\'s Office', '7', 'Md. Humayon Kabir Nayon', NULL, 'Personal Officer (Privilege)', 'Ministry of Social Welfare', 'nayan.mmad@gmail.com', NULL, '01712159863', NULL, NULL, NULL),
  ('8', 'Honorable State Minister\'s Office', '1', 'Ms. Farzana Sharmin', NULL, 'State Minister', 'Ministry of Social Welfare', 'state.min@msw.gov.bd', '+880 255100568', NULL, NULL, NULL, NULL),
  ('9', 'Honorable State Minister\'s Office', '2', 'Mohammad Nasim Ahmed', NULL, 'Private Secretary to the Honorable State Minister', 'Ministry of Social Welfare', 'ps.stateminister@msw.gov.bd', NULL, '01712082081', NULL, NULL, NULL),
  ('10', 'Honorable State Minister\'s Office', '3', 'Md. Abdus Salam', NULL, 'Assistant Private Secretary to the Honorable State Minister', 'Ministry of Social Welfare', 'abdussalam211070@gmail.com', NULL, '01740-599144', NULL, NULL, NULL),
  ('11', 'Honorable State Minister\'s Office', '4', 'Delowar Hossain', NULL, 'Personal Officer (Office of the Hon\'ble State Minister)', 'Ministry of Social Welfare', 'delowarmsw@gmail.com', '+880 255100568', '01517828802', NULL, NULL, NULL),
  ('12', 'Honorable State Minister\'s Office', '5', 'Md. Munsur Rahman', NULL, 'Personal Officer to State Minister (Privilege)', 'Ministry of Social Welfare', 'mrahman231186@gmail.com', NULL, '01719-303048', NULL, NULL, NULL),
  ('13', 'Office of the Secretary', '1', 'Dr. Mohammad Abu Yusuf', NULL, 'Secretary', 'Ministry of Social Welfare', 'sec@msw.gov.bd', '02-55100452', '01713277766', '103', '309', NULL),
  ('14', 'Office of the Secretary', '2', 'Md. Abdullah Al Mamun', NULL, 'Senior Assistant Secretary (Private Secretary to Secretary)', 'Ministry of Social Welfare', 'pssec@msw.gov.bd', '02223356684', '01303717666', '108', '311', NULL),
  ('15', 'Office of the Secretary', '3', 'Md. Shahin Alom', NULL, 'Personal Officer to Secretary', 'Ministry of Social Welfare', 'shahinalomtaj@gmail.com', '+8802 55100452', '01404119971', NULL, '311', NULL),
  ('16', 'Department of Administration', '1', 'Md. Kamal Uddin Biswas', NULL, 'Additional Secretary', 'Ministry of Social Welfare', 'acsadmin@msw.gov.bd', '+880 2223356682', '01715690818', NULL, '305', NULL),
  ('17', 'Department of Administration', '2', 'Rokeya Begum', NULL, 'Joint Secretary (Administration-1); Addl. Charge: Administration-2', 'Ministry of Social Welfare', 'jsadmin@msw.gov.bd', NULL, '01711265400', NULL, NULL, NULL),
  ('18', 'Department of Administration', '3', 'Md. Robiul Islam', NULL, 'Deputy Secretary (Administration-04)', 'Ministry of Social Welfare', 'dsadmin4@msw.gov.bd', NULL, '01715298400', NULL, NULL, NULL),
  ('19', 'Department of Administration', '4', 'Md. Masudul Haque Bhuiyan', NULL, 'System Analyst', 'Ministry of Social Welfare', 'sa@msw.gov.bd', '+8802 9514093', '+880 1915026423', '144', NULL, '+8802 9576680'),
  ('20', 'Department of Administration', '5', 'Shirin Sultana', NULL, 'Deputy Secretary (Parliament & Promise / Administration-3)', 'Ministry of Social Welfare', 'shirinsultana7153@gmail.com', '55100760', '01552457153', '143', NULL, NULL),
  ('21', 'Department of Administration', '6', 'Zohirul Islam', NULL, 'Senior Assistant Secretary (Administration-5 Branch)', 'Ministry of Social Welfare', 'bcs35zoi@gmail.com', NULL, '01724189010', NULL, NULL, NULL),
  ('22', 'Department of Administration', '7', 'Md. Ishahaque Ali', NULL, 'Senior Assistant Secretary (Administration-2)', 'Ministry of Social Welfare', 'ishahaque.info@gmail.com', NULL, '01735246154', NULL, NULL, NULL),
  ('23', 'Department of Administration', '8', 'Md. Jakir Hossain', NULL, 'Programmer', 'Ministry of Social Welfare', 'sumonzseluk@gmail.com', '+8802 55100393', '01727870346', NULL, NULL, NULL),
  ('24', 'Department of Administration', '9', 'Most. Selina Sultana', NULL, 'Assistant Secretary (Case); Addl. Charge: Law Cell and Rules', 'Ministry of Social Welfare', 'selinasultana1973@gmail.com', NULL, '01939968111', NULL, NULL, NULL),
  ('25', 'Department of Administration', '10', 'Md. Alimul Azim', NULL, 'Accounts Officer (DDO); Addl. Charge: Family Card Program', 'Ministry of Social Welfare', 'accounts@msw.gov.bd', '+8802-55100574', '01817533475', '118', NULL, NULL),
  ('26', 'Department of Administration', '11', 'Mirza Mahmud Suhreed', NULL, 'Assistant Programmer', 'Ministry of Social Welfare', 'ap@msw.gov.bd', '02-9546280', NULL, NULL, NULL, NULL),
  ('27', 'Department of Administration', '12', 'Forkan Ahmed Khan', NULL, 'Administrative Officer (Administration-1)', 'Ministry of Social Welfare', 'forkankhan206@gmail.com', '+8802 9549042', '+880 1918337767', NULL, NULL, '+8802 9514113'),
  ('28', 'Department of Administration', '13', 'Mohammad Abul Kalam Azad', NULL, 'Personal Officer (Legal Branch)', 'Ministry of Social Welfare', 'azadmsw@gmail.com', '+8802223356682', '+8801912309457', NULL, NULL, NULL),
  ('29', 'Department of Administration', '14', 'Md. Abdus Salam', NULL, 'Administrative Officer (Administration-II); Addl. Charge: Receiving and Dispatch', 'Ministry of Social Welfare', 'salam061615@gmail.com', '02-9546082', '+8801911686525', NULL, NULL, '+8802 9576680'),
  ('30', 'Department of Administration', '15', 'Nurunnahar', NULL, 'Personal Officer (Administration-2)', 'Ministry of Social Welfare', 'naharmsw13@gmail.com', '9576686', '01683018173', NULL, NULL, '+8802 9576680'),
  ('31', 'Department of Administration', '16', 'Farhana Jahan', NULL, 'Administrative Officer (Administration-5, Administration & Discipline)', 'Ministry of Social Welfare', 'shemul1977@gmail.com', '02-9546281', '01827907450', NULL, NULL, NULL),
  ('32', 'Department of Administration', '17', 'Mohammad Jamal Uddin', NULL, 'Administrative Officer (Administration-3, Parliament and Promises)', 'Ministry of Social Welfare', 'jamaluddin1451990@gmail.com', NULL, '01683726964', NULL, NULL, NULL),
  ('33', 'Department of Administration', '18', 'Masuma Sultana', NULL, 'Administrative Officer (Administration-4)', 'Ministry of Social Welfare', 'smasuma20@gmail.com', NULL, '01734540634', NULL, NULL, NULL),
  ('34', 'Department of Administration', '19', 'Piyas Dhar', NULL, 'Personal Officer (Administration Division)', 'Ministry of Social Welfare', 'piyas.mithu@gmail.com', NULL, '01725273956', NULL, NULL, NULL),
  ('35', 'Department of Administration', '20', 'Md. Alomgir Kabir', NULL, 'Administrative Officer (Training Branch)', 'Ministry of Social Welfare', 'alomgirmsw2016@gmail.com', NULL, '01722732219', NULL, NULL, NULL),
  ('36', 'Department of Administration', '21', 'Md. Sydul Islam', NULL, 'Administrative Officer (Receive and Dispatch)', 'Ministry of Social Welfare', 'sydulislam1972@gmail.com', NULL, '01725370806', NULL, NULL, NULL),
  ('37', 'Department of Administration', '22', 'Sohidul Islam', NULL, 'Personal Officer (Administration-01)', 'Ministry of Social Welfare', 'sohidul01021991@gmail.com', NULL, '01735325448', NULL, NULL, NULL),
  ('38', 'Department of Budget & Performance Evaluation', '1', 'Nargis Khanum', NULL, 'Additional Secretary (Budget, Social Security Programs & Evaluation); Addl. Charge: Planning and Development', 'Ministry of Social Welfare', 'adsplan@msw.gov.bd', NULL, NULL, NULL, NULL, NULL),
  ('39', 'Department of Budget & Performance Evaluation', '2', 'Mostafa Kamal', NULL, 'Additional Secretary (Budget, Activities and Evaluation Wing)', 'Ministry of Social Welfare', 'adsbud@msw.gov.bd', '55101186', NULL, NULL, NULL, NULL),
  ('40', 'Department of Budget & Performance Evaluation', '3', 'S. M. Noman Hasan Khan', NULL, 'Deputy Secretary (Budget and Management)', 'Ministry of Social Welfare', 'smnhkhan2020@gmail.com', '01552542439', '01552542439', NULL, NULL, NULL),
  ('41', 'Department of Budget & Performance Evaluation', '4', 'Md. Abdullah al Mamun Talukder', NULL, 'Deputy Secretary (Programme and Activities Monitoring)', 'Ministry of Social Welfare', 'abdullahshovon27@gmail.com', NULL, '+8801917001034', NULL, NULL, NULL),
  ('42', 'Department of Budget & Performance Evaluation', '5', '[Name in Bengali - verify]', NULL, 'Deputy Secretary (Family Card Program)', 'Ministry of Social Welfare', 'shoque.nbr@gmail.com', NULL, '01727132266', NULL, NULL, NULL),
  ('43', 'Department of Budget & Performance Evaluation', '6', 'Russel Ahmed', NULL, 'Deputy Secretary (Budget)', 'Ministry of Social Welfare', 'russelahmed_bd@yahoo.com', NULL, '01714088052', NULL, NULL, NULL),
  ('44', 'Department of Budget & Performance Evaluation', '7', 'Sukanta Saha', NULL, 'Senior Assistant Secretary (Social Security-03); Addl. Charge: Social Security-01', 'Ministry of Social Welfare', 'sukanto_sust14@yahoo.com', NULL, '01723952610', NULL, NULL, NULL),
  ('45', 'Department of Budget & Performance Evaluation', '8', 'Mohammad Shafiqul Islam', NULL, 'Senior Assistant Secretary (Social Security-02 Branch)', 'Ministry of Social Welfare', 'shafiqul33bcs@gmail.com', NULL, '01986307649', NULL, NULL, NULL),
  ('46', 'Department of Budget & Performance Evaluation', '9', '[Name in Bengali - verify]', NULL, 'Senior Assistant Secretary (Social Security-02)', 'Ministry of Social Welfare', NULL, NULL, NULL, NULL, NULL, NULL),
  ('47', 'Department of Budget & Performance Evaluation', '10', 'Md. Sirazul Haque', NULL, 'Assistant Secretary (Performance Management Branch); Attachment: Planning and Development-1', 'Ministry of Social Welfare', 'mdsirajulhaque61@gmail.com', NULL, '01715538282', NULL, NULL, NULL),
  ('48', 'Department of Budget & Performance Evaluation', '11', 'Md. Mozammel Haque Khan', NULL, 'Assistant Secretary (Research, Publication and Evaluation Branch)', 'Ministry of Social Welfare', 'mozammelhoquekhan72@gmail.com', '+8802 55100169', '01341677833', NULL, NULL, '+8802 9526680'),
  ('49', 'Department of Budget & Performance Evaluation', '12', 'Mohammad Alauddin', NULL, 'Assistant Secretary (Audit); Addl. Charge: Protocol Officer', 'Ministry of Social Welfare', 'alauddin1111@gmail.com', NULL, '01711159071', NULL, NULL, NULL),
  ('50', 'Department of Budget & Performance Evaluation', '13', 'Mohammad Monirul Islam', NULL, 'Administrative Officer (Audit)', 'Ministry of Social Welfare', 'mrepon78@gmail.com', NULL, '+8801772844720', NULL, NULL, '+8802 9576685'),
  ('51', 'Department of Budget & Performance Evaluation', '14', 'Mohammad Amanul Haq Bhuiyan', NULL, 'Administrative Officer (Social Security-03); Addl. Charge: Research, Publication and Evaluation', 'Ministry of Social Welfare', 'amanulmsw@gmail.com', '+8802 9514643', '+8801911007378', NULL, NULL, '+8809511056'),
  ('52', 'Department of Budget & Performance Evaluation', '15', 'Md. Manik Hossain', NULL, 'Administrative Officer (Performance Management Branch); Addl. Charge: Bangladesh Rehabilitation Council', 'Ministry of Social Welfare', 'manik.msw86@gmail.com', '+8802 9549040', '+880 1737620966', NULL, NULL, NULL),
  ('53', 'Department of Budget & Performance Evaluation', '16', 'Md. Abbas Ali', NULL, 'Administrative Officer (Family Card Program)', 'Ministry of Social Welfare', 'abbasmsw17@gmail.com', '+8802 9514643', '01913606935', NULL, NULL, NULL),
  ('54', 'Department of Budget & Performance Evaluation', '17', 'Atiqul Islam', NULL, 'Administrative Officer (Social Security-01); Addl. Charge: Social Security-02', 'Ministry of Social Welfare', 'didar.mosw@gmail.com', NULL, '01915924172', NULL, NULL, NULL),
  ('55', 'Department of Institutions and Disabilities', '1', 'Bijoy Krishna Debnath', NULL, 'Additional Secretary (Wing of Institutions and Disability)', 'Ministry of Social Welfare', 'addl.sec.pp@msw.gov.bd', '55100825', '+880 1711984911', '107', NULL, '+8802 9576680'),
  ('56', 'Department of Institutions and Disabilities', '2', 'Alaya Khatun', NULL, 'Additional Secretary', 'Ministry of Social Welfare', 'js.institution@msw.gov.bd', NULL, '01995085931', NULL, NULL, NULL),
  ('57', 'Department of Institutions and Disabilities', '3', 'Dr. Amitavo Chakrabartty', NULL, 'Deputy Secretary (NDD and Autism Branch)', 'Ministry of Social Welfare', 'amitavodvm@gmail.com', NULL, '01712206844', NULL, NULL, NULL),
  ('58', 'Department of Institutions and Disabilities', '4', '[Name in Bengali - verify]', NULL, 'Deputy Secretary (Disability); Addl. Charge: Performance-2', 'Ministry of Social Welfare', NULL, NULL, '01710750178', NULL, NULL, NULL),
  ('59', 'Department of Institutions and Disabilities', '5', 'Kazi Mahbub Ur Rahman', NULL, 'Deputy Secretary (Special Schools)', 'Ministry of Social Welfare', 'kazimasnoon109@gmail.com', NULL, '01884546456', NULL, NULL, NULL),
  ('60', 'Department of Institutions and Disabilities', '6', '[Name in Bengali - verify]', NULL, 'Senior Assistant Secretary (Disability)', 'Ministry of Social Welfare', NULL, NULL, NULL, NULL, NULL, NULL),
  ('61', 'Department of Institutions and Disabilities', '7', 'Mahmoda Yeasmin', NULL, 'Assistant Secretary (Institutions-1)', 'Ministry of Social Welfare', 'yeasminmahmoda@yahoo.com', '55100826', '01746111701', '134', NULL, NULL),
  ('62', 'Department of Institutions and Disabilities', '8', '[Name in Bengali - verify]', NULL, 'Assistant Secretary (Institution-2)', 'Ministry of Social Welfare', NULL, NULL, NULL, NULL, NULL, NULL),
  ('63', 'Department of Institutions and Disabilities', '9', 'Mohammed Fazlul Haque Bhuiyan', NULL, 'Administrative Officer (NDD & Autism Wing); Addl. Charge: Disability', 'Ministry of Social Welfare', 'mswndd@gmail.com', '+8802 9514093', '01916570416', NULL, NULL, '+8802 9576680'),
  ('64', 'Department of Institutions and Disabilities', '10', 'Afreen Islam', NULL, 'Personal Officer (Institution and Disability)', 'Ministry of Social Welfare', 'afreenswapon@gmail.com', '+8802 55100825', '+8801680052996', NULL, NULL, '+8802 9576680'),
  ('65', 'Department of Institutions and Disabilities', '11', 'Md. Atiqur Rahman', NULL, 'Administrative Officer (Budget)', 'Ministry of Social Welfare', 'atiqurmsw@gmail.com', '9615534', '01736974886', NULL, NULL, NULL),
  ('66', 'Department of Institutions and Disabilities', '12', 'Rubina Akter', NULL, 'Administrative Officer (Disability); Addl. Charge: Institution-1 & Institution-2', 'Ministry of Social Welfare', 'rubina.msw2023@gmail.com', NULL, '01726296836', NULL, NULL, NULL),
  ('67', 'Planning, Development and Law Department', '1', 'Nargis Khanum', NULL, 'Additional Secretary (Budget, Social Security Programs & Evaluation); Addl. Charge: Planning and Development', 'Ministry of Social Welfare', 'adsplan@msw.gov.bd', NULL, NULL, NULL, NULL, NULL),
  ('68', 'Planning, Development and Law Department', '2', 'Mohammad Nazmul Ahsan', NULL, 'Joint Secretary (Planning and Development Branch)', 'Ministry of Social Welfare', 'jsplan@msw.gov.bd', '55100808', '01711960806', '145', NULL, NULL),
  ('69', 'Planning, Development and Law Department', '3', 'Dr. Kazi Kamrun Nahar', NULL, 'Joint Secretary (Legal Wing); Addl. Charge: Monitoring and Evaluation', 'Ministry of Social Welfare', 'js.law@msw.gov.bd', NULL, '01552327231', NULL, NULL, NULL),
  ('70', 'Planning, Development and Law Department', '4', 'Shampa Kundu', NULL, 'Deputy Secretary (Planning and Development-2)', 'Ministry of Social Welfare', NULL, '55100456', '01717314203', '141', NULL, NULL),
  ('71', 'Planning, Development and Law Department', '5', 'Mohammad Selim Hossain', NULL, 'Senior Assistant Secretary (Planning and Development-1)', 'Ministry of Social Welfare', 'hossainselim13@gmail.com', NULL, '01715055083', NULL, NULL, NULL),
  ('72', 'Planning, Development and Law Department', '6', 'Md. Ahsan Habib', NULL, 'Assistant Secretary (Organization)', 'Ministry of Social Welfare', 'ahabib0700@gmail.com', NULL, '01552463849', NULL, NULL, NULL),
  ('73', 'Planning, Development and Law Department', '7', 'Md. Liton Mia', NULL, 'Administrative Officer (Corporate and Litigation Branch)', 'Ministry of Social Welfare', 'litonmia3494@gmail.com', NULL, '01315426822', NULL, NULL, NULL),
  ('74', 'Planning, Development and Law Department', '8', 'Al Jubaed Tanim', NULL, 'Administrative Officer (Planning and Development-I)', 'Ministry of Social Welfare', 'mswplanone@gmail.com', NULL, '01914-804244', NULL, NULL, NULL),
  ('75', 'Planning, Development and Law Department', '9', 'Md. Rajon Mia', NULL, 'Administrative Officer (Planning & Development-2)', 'Ministry of Social Welfare', 'rajonmia007@gmail.com', NULL, '01311704546', NULL, NULL, NULL),
  ('76', 'Planning, Development and Law Department', '10', 'Sharmin Sultana', NULL, 'Personal Officer (Planning and Development Division)', 'Ministry of Social Welfare', 'sharmins226@gmail.com', '+880255101344', '018714103587', NULL, NULL, NULL),
  ('77', 'Planning, Development and Law Department', '11', 'Sahabul Amin', NULL, 'Personal Officer (Planning and Development Branch)', 'Ministry of Social Welfare', 'shakilaminmsw@gmail.com', NULL, '01911475249', NULL, NULL, NULL);
